AWSTemplateFormatVersion: 2010-09-09
Description: simple email service and related configs

Parameters:
  Domain:
    Type: String

#Conditions:
#Mappings:
#Metadata:

Resources:

  CustomLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeLambdaExecutionRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: SESDomainIdentityPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowSESDomainIdentityActions
            Effect: Allow
            Action:
            - ses:VerifyDomainDkim
            - ses:VerifyDomainIdentity
            - ses:DeleteIdentity
            Resource: "*"

  CustomBackedLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for lambda-backed cfn custom resource
      Runtime: python3.9
      Role: !GetAtt CustomLambdaExecutionRole.Arn
      Handler: index.lambda_handler
      Timeout: 90
      Environment:
        Variables:
          number: 10
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          import os
          
          def lambda_handler(event, context):
            number = os.environ['number']
            log = logging.getLogger()
            log.setLevel(logging.INFO)
            print(event)
            name = event['ResourceProperties']['Domain']
            responseData = {}

            try:
              if event.get('RequestType') == 'Create':
                responseData['message'] = "Sending back what lambda got in the request - name: " + name
                responseData['number'] = "something else" + number
                log.info('created something')
                
              elif event.get('RequestType') == 'Delete':
                responseData['message'] = "Lambda saw the delete request"
                log.info('deleted whatever')

              else:
                responseData['message'] = "Nothing to do!"
                #log.error('Unknown operation: %s', event.get('RequestType'))
                log.info('Custom resource didnt do anything')
              
              # Set the status 'reason' in the response
              # this works but doesn't show in the cloudformation console
              ## reason = "is this the reason?"
              ## cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, '', '', reason)
            
            # Rollback gracefully on any unexpected errors
            except Exception:
              log.exception('Signaling failure to CloudFormation.')
              cfnresponse.send(event, context, cfnresponse.FAILED, {})

  InvokeCustomLambda:
    Type: Custom::InvokeCustomLambda
    Properties:
      ServiceToken: !GetAtt CustomBackedLambda.Arn
      Domain: !Ref Domain

# Create domain identity
# aws ses verify-domain-identity --domain example.com

# Create dkim records
# aws ses verify-domain-dkim --domain example.com

Outputs:
  CustomLambdaOutput: 
    Description: Message from custom lambda
    Value: !GetAtt InvokeCustomLambda.message