AWSTemplateFormatVersion: 2010-09-09
Description: simple email service and related configs

Parameters:
  ZoneName:
    Type: String
  ZoneId:
    Type: String

#Conditions:
#Mappings:
#Metadata:

Resources:

  CustomLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeLambdaExecutionRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: SESDomainIdentityPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AllowSESDomainIdentityActions
            Effect: Allow
            Action:
            - ses:VerifyDomainDkim
            - ses:VerifyDomainIdentity
            - ses:DeleteIdentity
            Resource: "*"
          - Sid: AlowRoute53Actions
            Effect: Allow
            Action:
            - route53:ChangeResourceRecordSets
            Resource: !Sub "arn:aws:route53:::hostedzone/${ZoneId}"

  CustomBackedLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function for lambda-backed cfn custom resource
      Runtime: python3.9
      Role: !GetAtt CustomLambdaExecutionRole.Arn
      Handler: index.lambda_handler
      Timeout: 90
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import logging
          import os
          
          def lambda_handler(event, context):

            log = logging.getLogger()
            log.setLevel(logging.INFO)
            print(event)
            responseData = {}

            try:

              request = event['RequestType']
              properties = event['ResourceProperties']
              name = properties['ZoneName']
              id = properties['ZoneId']

              # CREATE and UPDATE events are effectively the same because
              # Changes to custom resource properties will cause cfn to create a new resource and delete the old one
              if request == 'Create' or 'Update':
                responseData['message'] = "Lambda saw the CREATE/UPDATE request"
                print(properties)
                #print("Lambda got 'ZoneName' in the request: " + name)
                #print("Lambda got 'ZoneId' in the request: " + id)
                log.info('lambda did something with CREATE/UPDATE')

              # 'ResourceProperties' in DELETE events are the same as 'OldResourceProperties' in UPDATE events
              elif request == 'Delete':
                responseData['message'] = "Lambda saw the DELETE request"
                print(properties)
                log.info('lambda did something with DELETE')

              else:
                responseData['message'] = "Nothing to do!"
                log.info('Lambda didnt do anything')

            # Rollback gracefully on any unexpected errors
            except Exception:
              log.exception('Signaling failure to CloudFormation.')
              cfnresponse.send(event, context, cfnresponse.FAILED, {})
            
            else:
              # Always send SUCCESS back to cfn if lambda did what it was supposed to do
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
              
              # This works but doesn't show in the cloudformation console
              ## reason = "enter a custom reason here"
              ## cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, '', '', reason)

  InvokeCustomLambda:
    Type: Custom::InvokeCustomLambda
    Properties:
      ServiceToken: !GetAtt CustomBackedLambda.Arn
      ZoneName: !Ref ZoneName
      ZoneId: !Ref ZoneId

# Create domain identity
# aws ses verify-domain-identity --domain example.com

# Create dkim records
# aws ses verify-domain-dkim --domain example.com

Outputs:
  CustomLambdaOutput: 
    Description: Message from custom lambda
    Value: !GetAtt InvokeCustomLambda.message