AWSTemplateFormatVersion: 2010-09-09
Description: static website with cloudfront s3 lambda route53

Parameters:
  Domain:
    Type: String
  ZoneId:
    Type: String
  Env:
    Type: String
    AllowedValues:
      - "dev"
      - "prod"
  UseLegacy:
    Type: String
    AllowedValues:
      - "true"
      - "false"
  UseCf:
    Type: String
    AllowedValues:
      - "yes"
      - "no"

Conditions:
  UseLegacyCond: !Equals [!Ref UseLegacy, 'true']
  UseCfCond: !Equals [!Ref UseCf, 'yes']
  ProdCond: !Equals [!Ref Env, 'prod']

Resources:

  Cmk1:
    Type: AWS::KMS::Key
    Properties:
      Description: CMK for KSK for DNSSEC
      Enabled: true
      EnableKeyRotation: false
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      KeyPolicy:
        Version: "2012-10-17"
        Id: Cmk1
        Statement:
          - Sid: Grant access to other iam principals
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: Grant access to dnssec service
            Effect: Allow
            Principal:
              Service: dnssec-route53.amazonaws.com
            Action:
              - kms:DescribeKey
              - kms:GetPublicKey
              - kms:Sign
            Resource: '*'
          - Sid: Restrict access to dnssec service
            Effect: Allow
            Principal:
              Service: dnssec-route53.amazonaws.com
            Action:
              - kms:CreateGrant
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: true

  CmkAlias1:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/Dnssec1
      TargetKeyId: !Ref Cmk1

  Ksk1:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref ZoneId
      KeyManagementServiceArn: !GetAtt Cmk1.Arn
      Name: Ksk1
      Status: ACTIVE

  Dnssec1:
    Type: AWS::Route53::DNSSEC
    DependsOn: Ksk1
    Properties:
      HostedZoneId: !Ref ZoneId

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaFunctionAddHeaders:
    Type: AWS::Lambda::Function
    Properties:
      Description: Add http headers
      Handler: 'index.handler'
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Timeout: 25
      Code:
        ZipFile: |
          'use strict';

          exports.handler = (event, context, callback) => {
            const response = event.Records[0].cf.response;
            const headers = response.headers;

            headers['Strict-Transport-Security'] = [{
              key: 'Strict-Transport-Security',
              value: 'max-age=31536000; includeSubdomains; preload'
            }];

            callback(null, response);
          };

  LambdaVersionAddHeadersv1:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunctionAddHeaders

  LambdaFunctionRedirect:
    Type: AWS::Lambda::Function
    Properties:
      Description: Host based redirect
      Handler: 'index.handler'
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Timeout: 5
      Code:
        ZipFile: !Sub 
          - | 
            'use strict';

            exports.handler = (event, context, callback) => {
              let request = event.Records[0].cf.request;
              let host = request.headers.host[0].value;
              let url = 'https://${TargetDNS}' + request.uri;

              if (host == "${RedirectDNS}") {
                var response = {
                  status: '301',
                  statusDescription: 'Moved Permanently',
                  headers: {
                    'location': [{
                      key: 'Location',
                      value: url,
                    }],
                  },
                };
                callback(null, response);
              }
              else {
                callback(null, request);
              }
            };
          - TargetDNS: !If [ProdCond, !Sub "www.${Domain}", !Sub "www.${Env}.${Domain}"]
            RedirectDNS: !If [ProdCond, !Ref Domain, !Sub "${Env}.${Domain}"]

  LambdaVersionRedirectv10:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LambdaFunctionRedirect

  AcmCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If
        - ProdCond
        - !Ref Domain
        - !Sub ${Env}.${Domain}
      DomainValidationOptions:
        - DomainName: !If
          - ProdCond
          - !Ref Domain
          - !Sub ${Env}.${Domain}
          HostedZoneId: !Ref ZoneId
      ValidationMethod: DNS
      SubjectAlternativeNames: !If
        - ProdCond
        - 
          - !Sub www.${Domain}
        - 
          - !Sub www.${Env}.${Domain}

  r53RecordGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref ZoneId
      RecordSets:
        !If 
        - UseLegacyCond
        -
          - Name: !If
              - ProdCond
              - !Sub "www.${Domain}"
              - !Sub "www.${Env}.${Domain}"
            Type: A
            ResourceRecords:
              - 192.168.1.222
            TTL: 900
        -
          - Name: !If
              - ProdCond
              - !Sub "www.${Domain}"
              - !Sub "www.${Env}.${Domain}"
            Type: A
            AliasTarget:
              DNSName: !GetAtt CfDist.DomainName
              HostedZoneId: Z2FDTNDATAQYW2
          - Name: !If
              - ProdCond
              - !Sub "www.${Domain}"
              - !Sub "www.${Env}.${Domain}"
            Type: AAAA
            AliasTarget:
              DNSName: !GetAtt CfDist.DomainName
              HostedZoneId: Z2FDTNDATAQYW2

  r53RecordGroupRedirect:
    Type: AWS::Route53::RecordSetGroup
    DependsOn: r53RecordGroup
    Properties:
      HostedZoneId: !Ref ZoneId
      RecordSets:
        !If 
        - UseLegacyCond
        - 
          - Name: !If
              - ProdCond
              - !Sub "${Domain}"
              - !Sub "${Env}.{Domain}"
            Type: A
            ResourceRecords:
              - 192.168.1.222
            TTL: 900
        - 
          - Name: !If
              - ProdCond
              - !Sub "${Domain}"
              - !Sub "${Env}.${Domain}"
            Type: A
            AliasTarget:
              DNSName: !If
                - ProdCond
                - !Sub "www.${Domain}"
                - !Sub "www.${Env}.${Domain}"
              HostedZoneId: !Ref ZoneId
          - Name: !If
              - ProdCond
              - !Sub "${Domain}"
              - !Sub "${Env}.${Domain}"
            Type: AAAA
            AliasTarget:
              DNSName: !If
                - ProdCond
                - !Sub "www.${Domain}"
                - !Sub "www.${Env}.${Domain}"
              HostedZoneId: !Ref ZoneId

  CfOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'for onegovee2 cf dist'

  CfDist:
    Type: AWS::CloudFront::Distribution
    Condition: UseCfCond
    DependsOn:
      - S3BucketPolicy
    Properties:
      DistributionConfig:
        Aliases: !If
          - ProdCond
          - 
            - !Sub "www.${Domain}"
            - !Sub "${Domain}"
          - 
            - !Sub "www.${Env}.${Domain}"
            - !Sub "${Env}.${Domain}"
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCert
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - Id: !GetAtt S3Bucket.RegionalDomainName
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CfOai]]
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
          LambdaFunctionAssociations:
            - EventType: 'origin-response'
              LambdaFunctionARN: !Join
                - ':'
                - - !GetAtt [LambdaFunctionAddHeaders, Arn]
                  - !GetAtt [LambdaVersionAddHeadersv1, Version]
            - EventType: 'viewer-request'
              LambdaFunctionARN: !Join 
                - ':'
                - - !GetAtt [LambdaFunctionRedirect, Arn]
                  - !GetAtt [LambdaVersionRedirectv10, Version]
          TargetOriginId: !GetAtt S3Bucket.RegionalDomainName
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100

  S3Bucket:
    Type: AWS::S3::Bucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CfOai.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Join ['', [!GetAtt S3Bucket.Arn, "/*"]]