AWSTemplateFormatVersion: 2010-09-09
Description: web application firewall and related configs

Parameters:
  AllowedCidrs:
    Type: CommaDelimitedList
#Conditions:
#Mappings:
#Metadata:

Resources:

  AllowIpSetList:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses: !Ref AllowedCidrs
      IPAddressVersion: IPV4
      Scope: CLOUDFRONT

  Wafv2CustomWebAcl1:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Block: {}
      Scope: CLOUDFRONT
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: CustomWebAcl1
      Rules:
        - Name: cloudfront-url-block
          Priority: 0
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockCfUrl
          Statement:
            AndStatement:
              Statements:
              - IPSetReferenceStatement:
                  Arn: !GetAtt AllowIpSetList.Arn
              - ByteMatchStatement:
                  FieldToMatch:
                    SingleHeader:
                      Name: host
                  PositionalConstraint: CONTAINS
                  SearchString: onegovee2.com
                  TextTransformations:
                  - Type: NONE
                    Priority: 0

Outputs:
  CustomWebAcl1Arn:
    Description: ARN of the custom web acl to block cloudfront url
    Value: !GetAtt Wafv2CustomWebAcl1.Arn